"""empty message

Revision ID: 14319cee57ee
Revises: 8e446144350e
Create Date: 2024-08-18 16:20:43.473971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14319cee57ee'
down_revision = '8e446144350e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comments', schema=None) as batch_op:
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
