"""empty message

Revision ID: 51e38d1b4edd
Revises: d7f4db6814d3
Create Date: 2024-08-18 18:15:07.495787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51e38d1b4edd'
down_revision = 'd7f4db6814d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comments', schema=None) as batch_op:
        batch_op.alter_column('topic',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comments', schema=None) as batch_op:
        batch_op.alter_column('topic',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
