"""empty message

Revision ID: d7f4db6814d3
Revises: 14319cee57ee
Create Date: 2024-08-18 17:56:17.995296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7f4db6814d3'
down_revision = '14319cee57ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likecount', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Comments', schema=None) as batch_op:
        batch_op.drop_column('likecount')

    # ### end Alembic commands ###
